fos_rest:
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
    serializer:
        serialize_null: true
    format_listener:
        enabled: true
        rules:
          - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
          - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    exception:
        enabled: true
